# Generated by Django 4.1.5 on 2023-04-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_remove_recipe_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='publish',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
