# Generated by Django 4.1.7 on 2023-02-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_remove_recipe_ingredients_alter_recipe_r_desc_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regiatration',
            new_name='registration',
        ),
    ]
