# Generated by Django 4.1.5 on 2023-04-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_recipe_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.registration'),
        ),
    ]
