# Generated by Django 4.1.7 on 2023-02-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_rename_regiatration_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
