# Generated by Django 4.1.7 on 2023-02-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='r_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
