# Generated by Django 4.1.5 on 2023-03-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_alter_recipe_r_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_text', models.CharField(max_length=300)),
            ],
        ),
    ]
