# Generated by Django 4.1.5 on 2023-04-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_alter_registration_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
