# Generated by Django 4.1.5 on 2023-03-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='chef',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=0, max_length=3),
        ),
    ]
