# Generated by Django 4.1.5 on 2023-03-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_registration_chef'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.AddField(
            model_name='registration',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='path/to/images'),
        ),
    ]
