# Generated by Django 4.1.5 on 2023-03-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0008_delete_text_registration_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
