# Generated by Django 4.1.5 on 2023-03-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0009_alter_registration_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='pic',
            field=models.ImageField(default='profile.png', upload_to='profile_pics/'),
        ),
    ]
