# Generated by Django 4.1.5 on 2023-03-28 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0010_alter_registration_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='r_name',
            new_name='recipe_name',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='r_desc',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='r_id',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='NIL'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='non_veg',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default='food.png', upload_to='recipes/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='veg',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe_app.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(default='NIL'),
        ),
    ]
