# Generated by Django 4.1.5 on 2023-05-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0010_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
