# Generated by Django 4.1.5 on 2023-05-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0011_registration_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='is_verified',
        ),
    ]
