# Generated by Django 4.1.5 on 2023-03-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0011_rename_r_name_recipe_recipe_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dessert',
            field=models.BooleanField(default=0),
        ),
    ]
