# Generated by Django 4.1.5 on 2023-03-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0012_recipe_dessert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='chef',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
