# Generated by Django 4.1.5 on 2023-03-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0013_alter_registration_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='chef',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=0, max_length=3),
        ),
    ]
